### ISSUE TITLE
Constraint definitions in interface

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#101]
Some but not all constraints currently have hover-text definitions. These should be replaced by collapsible (collapsed by default) constraint definitions, explaining the SPOT implementation for all constraints.

ConstraintName<span class="info">
   <span class="content">
      Assign a violation for every... (Author Year). SPOT function: function_name.
     [The content in this span will be hidden by default and appear when the info symbol button is clicked.]
   </span>
</span>

**Comment by jbellik** [comment]
I think this got fixed in the EqualSistersBug branch but the commit seems to have been overwritten by subsequent merges. Can you pull it back out and re-commit it somehow? It would make sense to do that in the collapsible-interface branch.

**Comment by maxTarlov** [comment]
The constraint definitions have their own branch (constraint_definitions). I started that work in the equal sisters branch but removed it because I realized that the equal sisters bug would be fixed a lot earlier than the constraint definitions.

**Comment by jbellik** [comment]
@rbibbs will add citations to Google Doc
@jbellik  will add missing constraint definitions
@maxTarlov will check for standardization
@ivpetkov will put the text into the info content spans in the interface

**Comment by jbellik** [comment]
Comment here when your part is done. I've filled in all the missing definitions and added some for two constraints that I am about to add to the interface.

**Comment by rbibbs** [comment]
Both Richard & Jenny's portions are done. Max will be considering standardization this week. Once completed, Iva will copy-paste definitions.

**Comment by ivpetkov** [comment]
I added all the definitions to the interface.
