### ISSUE TITLE
obeysExhaustivity not working with boolean

### ISSUE THREAD

**Issue by maxTarlov** [syntax-prosody-ot/main#121]

**Comment by maxTarlov** [comment]
In testing the recursive category options in GEN, I found that obeysExhaustivity doesn't work with a boolean input, only with an array. When the value is set to true, no exceptions are raised but the output array of GEN is empty.
Try: GEN({}, 'first second', {obeysExhaustivity:true})

**Comment by jbellik** [comment]
It works fine in the master branch. What branch are you seeing this issue on?

**Comment by maxTarlov** [comment]
I was working on the recursive_GEN_options branch, so I guess that is an issue with my code. Sorry, I should have checked the master branch first.

**Comment by jbellik** [comment]
No problem. I tried it in the recursiveCategoriesGEN branch as well and it seems fine on my machine. Do you have unpushed changes? Or could it be a build issue?

**Comment by maxTarlov** [comment]
Ok, I think it must be some kind of issue with my test file. After running jsbuild.sh in the Recursive_GEN_options branch, I get two different results in different windows. When I run GEN({}, 'first second', {obeysExhaustivity:true}) in the console for the interface, I get a populated array. When I run the same function in the console for my test file (main/test/Recursive_GEN_options.html) I get an empty array.

**Comment by maxTarlov** [comment]
Ok, another interesting thing: I tried bringing my test file over to master so that none of the code I have written in GEN will work and I don't have the issue anymore. I just don't know why it matters which document I call GEN from back in Recursive_GEN_options. Maybe a cache issue? I tried loading fresh from source.

**Comment by maxTarlov** [comment]
I've figured it out. It has to do with some functionality I though would be helpful when users wanted to use categories in GEN that were not defined in pCat. I think that I will just add an alert if someone uses categories that are not defined n pCat.

**Comment by jbellik** [comment]
Sounds good.
