### ISSUE TITLE
Add to interface: GEN for reordering words + NoShift

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#124]
The interface currently only supports the standard GEN function, with options for exhaustivity, non-recursivity, tone annotation, and headedness. We have created backend functionality for evaluating data in which one word has moved in the output prosodic representation compared to its position in the input syntax (GENwithCliticMovement, noShift), but this needs to be added to the interface.

**Comment by jbellik** [comment]
To the "Syntax-prosody mapping" field set, add the constraint NoShift (calls the function noShift, defined in constraints/noShift.js; does not take a category argument). It should come with hovertext with this constraint definition: "Assign a violation if the terminals in the prosodic tree are not all in the same order as those in the syntactic tree."

To the section headed "Options for prosodic tree generation (GEN function)", add a checkbox "Allow clitics to move" with an info button that reveals this text: "GEN will permute the first node in the syntactic tree with category 'clitic' through the sentence. Ex.: a b c-clitic -> a b c-clitic, a c-clitic b, c-clitic a b. Only use this if your sentences are short, because for a sentence with _n_ words, this will multiply the number of prosodic trees by _n_." Checking this box should cause GENwithCliticMovement to be called, instead of regular GEN. (Both functions are defined in candidate_generator.js)

**Comment by jbellik** [comment]
You can check that it's working by comparing the output of GENwithCliticMovement({}, 'a b-clitic') in the JS console with the tree parenthesizations in the tableau when you use 'a b-clitic' as the input string for GEN.

**Comment by ColinAChen** [comment]
Where should the no shift option be added? I know we discussed this but I cannot remember. After that, I will submit a pull request.

**Comment by jbellik** [comment]
Let's put it under "Markedness constraints on horizontal relationships". It can go at the top, above EqualSisters. (That way we don't have to get it under a sub-heading.)
