### ISSUE TITLE
GEN for longer sentences

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#130]
Create an option for GEN where certain XPs are always matched.

**Comment by nkalivoda** [comment]
Should come with a warning along the lines of: "Warning! You are about to do CROT. Do you wish to proceed?"

**Comment by jbellik** [comment]
The intention behind this was to aid in replicating Bennett, Elfner & McCloskey 2016's analysis of weak pronouns in Irish, but after reviewing the data/analysis more closely, I think using it will give us a CROT analysis even in this case.
