### ISSUE TITLE
Make Match conflate sCats with identical terminals

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#137]
Elfner's definition of Match treats [[...xyz...]] as a single sCat, since the two dominate the same terminals. That is, failure to match [[...xyz...]] results in 1 violation, not 2.

We shouldn't expect users to know that they need to pre-trim their syntactic trees. They might put in [[...xyz...]] expecting Match to already work like Elfner says. So can we change the definition of Match to do this?

**Comment by jbellik** [comment]
I wonder if a better option would be to create a function that trims the strees, rather than bundling this into Match. Is relevant for Align as well as Match, for instance? Would we ever want to give [[...xyz...]] two violations?

**Comment by nkalivoda** [comment]
It will generally be relevant for Align too, but only because alignment analyses assume the Lexical Category Condition, which ensures that [[...xyz...]] will never arise. The bigger sCat here would be invisible by the LCC––not because it shares the terminal string of the smaller sCat, but because it has a silent head (presumably a trace or a functional projection; the LCC doesn't mention silent in situ lexical heads, since the issue never comes up, but this might be an exception).

I like the tree-trimming idea. We should do that instead of modifying Match. However, I think that:

(1) Inputs should still display with the full original bracketing from the user's sTree, even when nodes have been trimmed for Eval.
(2) It might be nice to have an option to turn this off (perhaps not on the interface, but possible for those in the know), just in case someone ever wanted to experiment with a different definition that actually counts both sCats in [[...xyz...]]. But this is really less important, and not interface-button-worthy.

**Comment by nkalivoda** [comment]
Also, this only applies to sCats with the same category. So two phis with the same terminal string, but not an iota and a phi with the same terminal string.

**Comment by jbellik** [comment]
Write 2 functions:
1. Take a syntactic tree and trim out all heads marked silent:true
2. Take a (trimmed) syntactic tree and trim out XP-XP configurations where both XPs have all and only the same terminals

**Comment by jbellik** [comment]
This function has been implemented and merged into master. However, we need to add it to the interface as an option.

**Comment by jbellik** [comment]
@nkalivoda , I am thinking we could add  this in either of 2 places on the interface:
1. under inputs -- since it has to do with how inputs are interpreted
2. under mapping constraints -- it's not a constraint but it's an option that is only relevant to the mapping constraints.

Which do you think is better? Please weigh in so Max can implement.

**Comment by nkalivoda** [comment]
I'd say under the inputs. The more prominent the better.
