### ISSUE TITLE
Fix enter button triggering "Get Results" in interface

### ISSUE THREAD

**Issue by rbibbs** [syntax-prosody-ot/main#140]
Currently when you are in a text box within the interface, i.e. either of the "String of Terminals" text box inputs", if you press Enter, it will trigger the Get Results button (rather than a closer button, such as "Go" to generate a tree from the string of terminals).

**Comment by jbellik** [comment]
please document specifics

**Comment by jbellik** [comment]
This seems to be triggered anywhere in the form. Disable "submit on keypress" to turn this off.

**Comment by ivpetkov** [comment]
I found a solution that disables the submit on enter after entering text in the text box, but it is still triggered if you press enter after checking a checkbox. I will keep looking for a solution that solves both problems.

**Comment by jbellik** [comment]
I think we should just not worry about this one. It's not that big of a problem, in my opinion.
