### ISSUE TITLE
matchMaxSyntax

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#145]
When I put 'matchMaxSyntax-xp' in my constraint set, the VT doesn't download, and in the js console I get this message:

Uncaught ReferenceError: options is not defined
    at matchMaxSyntax (spot.js:1784)
    at matchMaxSyntax (spot.js:1781)
    at makeTableau (spot.js:4577)
    at makeTableauCsvs (abstractMatch.html:125)
    at runDemo (abstractMatch.html:144)
    at spot.js:4490

When I put 'matchMaxSyntax' without an argument, the VT downloads, but  with 0 in every cell in the matchMaxSyntax column.

Does this need an argument other than 'xp'? Or have I done something else wrong? Or is there a bug?

**Comment by jbellik** [comment]
Sorry about that, the issue should be fixed now. Let me know if it's still a problem -- I didn't have time to test much but can look at it again if need be!
