### ISSUE TITLE
Toggle for showing/hiding the code-display of trees

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#157]
Create a toggle switch that shows/hides the code-view of syntactic trees.
See "input details" diagram in "wireframes with details" on Drive for more specifics.

**Comment by jbellik** [comment]
Put this right under the "Done" button in the tree-builder

**Comment by ColinAChen** [comment]
Do you want the selector to be a toggle switch like the interactive mockup has or is a simple checkbox sufficient? I think they are the same thing but the toggle switch requires some CSS.

**Comment by jbellik** [comment]
A checkbox is okay for now, although it would be nice to have the toggle
later if we have time.
