### ISSUE TITLE
GEN options: prosodic categories

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#161]
Add interface option to select categories to use for GEN
see wireframes with details

**Comment by jbellik** [comment]
- Take out the checkboxes
- Don't trigger the warning when nothing is specified

**Comment by maxTarlov** [comment]
I took out the checkboxes and the warning no longer triggers because of it, but I can't get the categories to line up. Changes in the gen-categories-update branch

**Comment by maxTarlov** [comment]
Got the categories to line up, changes have been merged into interface-reorg branch
