### ISSUE TITLE
Category display on interface

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#162]
Change interface to show all category selections on the line below their constraints (or GEN option).
See wireframes.

**Comment by jbellik** [comment]
Just do this for the constraints first to avoid merge conflicts

Iva will research how to get things lined up

**Comment by jbellik** [comment]
Each row of categories should be in a one-row table underneath its constraint. Set the width of each <td> to some consistent number.

**Comment by ColinAChen** [comment]
Do you want line breaks between the constraint and sub constraint like in the wireframe?

**Comment by jbellik** [comment]
Functionality: 
- The basic layout looks okay in the syntax-prosody mapping section (apart from Match, which I know I said not to do yet, to avoid merge conflicts with Iva's feature branch)
- Something weird is happening with the position of the info buttons -- when I select a constraint, its info button moves leftward. I think this is because displaying the 2nd row changes the table to have 3 columns instead of two.
- All other sections: The category selections haven't been moved to their own rows, so the non-initial constraints are being hidden instead of the categories being hidden!

Aesthetics: 
- Please figure out a way to indent the category row
- The width of each <td> element should be smaller. It looks weird having so much space between the categories. 
- I also want to incorporate the underlining of selected constraints, like in the wireframe.

Technical comments: I'm not sure it really works to have the constraint name + info button in the same table as the category selection, because they are going to require different alignments. The constraint names need to be able to take up more width than a cell of the category row does. Plus, expanding the constraint info is going to be problematic with this data structure, because we want the constraint info to be able to display across the entire width of the fieldset.

Refer to constraint_details.png in the ["wireframes with details" folder](https://drive.google.com/drive/u/0/folders/1Fdy3iAC3OI--o2s1_bGNBPdnvMOcVxuW) in Drive.

**Comment by jbellik** [comment]
I did some experimentation / research on layout options and I am second-guessing the table-based layout. I think we would actually do better to use <span>s or <div>s with "display: inline-block". We had previously discarded those possibilities because <span> by default doesn't have a width attribute, and <div> by default occurs on a new line, but I found out that by setting the display attribute, these defaults can be overridden.

So ideally we could actually move away from the tables altogether, and convert everything to some combination of <div>s and <span>s. This would get us out of having so many table-related tags plus our issues with needing different element widths on alternating rows.

**Comment by ColinAChen** [comment]
Are constraint titles (the hover text) going to maintained or will they be removed because of the info buttons? If they are going to be kept, should they be displayed when hovering over the info button or just the constraint text/checkbox?

**Comment by jbellik** [comment]
We should remove those. Good catch.
