### ISSUE TITLE
Make the top (not the results) a consistent width that scales with window

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#164]

**Comment by jbellik** [comment]
* make the main div width smaller
* adjust the fieldset css to not override the main div width

**Comment by ColinAChen** [comment]
The sizing changes after getting the results. Everything resizes to the length of the table if it is longer than the current width. Should the rest of the page be independent of the results' width?

**Comment by jbellik** [comment]
Good catch. It would be better if the upper part of the page did not resize to match the width of the tableau, although I don't know of a simple way to do that.
