### ISSUE TITLE
Visual signal that "Done!" button worked

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#167]
With the addition of the toggle switch for the code view, there is no obvious way to tell that button "Done! Add trees to analysis" has done anything. You have to open the code view to tell. We need some kind of visual signal that the button has worked. 

Possibilities: 
- Text that appears on the side saying something like: "The trees in the analysis are up-to-date", and which disappears either after a brief delay or the next time anything changes in the tree-builder GUI.
or:
- Button becomes disabled (unclickable / a different color?) until something changes in the tree-builder

@ivpetkov, which solution seems better to you? You don't necessarily have to be the one to implement it but I'd like your opinion on the design.

**Comment by ivpetkov** [comment]
I like the idea of text appearing to the side better than disabling the done button. Disabling the done button may make for a bad user experience if it's not clear to the user why the button is disabled.
