### ISSUE TITLE
built in analysis reset

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#175]
Make the page reset automatically before loading a new built-in system

**Comment by maxTarlov** [comment]
I have made a reset function that runs whenever my_built_in_analysis() runs, but this function is different from what the Clear All button does, which is force the browser to reload ignoring its cache. This functionality is useful for browsers like FireFox, which load from the cache and make things difficult, but it is going to be much slower than the new function once it is on the internet. Should I replace the reload functionality of the Clear All button with the clear function?

**Comment by jbellik** [comment]
1. It looks like the reset function clearAnalysis() is setting the toggle switch for the codeview to false as well, so now the codeview of the trees isn't displaying when a built-in system is selected. Can you fix that? (I tried what I thought would be a quick fix in the built_in_analysis function but it didn't work.) 

2. I think changing the Clear All button to reset all the checkboxes would make sense. We have had issues with the online version of the interface loading from cache and consequently not showing updates, but a) I think I have a different work-around for that, and b) it would not be good to have the interface suddenly update when you click the "Clear All" button!

**Comment by jbellik** [comment]
3. As I look at the wireframes, I realize that the clear button is actually supposed to get relocated to the bottom of the page, next to the save and load buttons. See closed_layout_wireframe_2.png in Drive/SPOT_for_RAs/Interface design materials. And we decided that we don't need the "go" button next to the dropdown although that's still in the wireframe.

**Comment by maxTarlov** [comment]
I have fixed the clearAnalysis function so that it only interacts with the constraints and genOptions and doesn't clear out all the constraint-categories and mess with the tree code switch. I also changed the Clear All button to call the clearAnalysis function rather than reloading the page. I will move the Clear All button once I get the Save/Load functionality working
