### ISSUE TITLE
Add section to allow selection of categories to ignore in tree parenthesization

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#181]
This should go under "Tree annotation options"
See wireframes for more details.

**Comment by maxTarlov** [comment]
In the wireframe, "don't show nodes of category" has four options: I, P, W and "other." Are there other categories that we would want to hide? Should this just be I, P, W, Ft, Syll?

**Comment by jbellik** [comment]
I was considering a write-in option in case people use custom categories,
but since the interface doesn't support custom GEN categories (and
shouldn't right now), I think we can just use {i, phi, w}. There's no point
putting foot and syll as options because we never use parents for terminals
anyway.

**Comment by maxTarlov** [comment]
ok, I've removed Ft and syll from the hide-able categories

**Comment by maxTarlov** [comment]
The changes associated with this issue have been merged into the save-load_analysis branch since these changes are dependent on that branch and there is currently an open pull request for that branch.
