### ISSUE TITLE
Clearing trees

### ISSUE THREAD

**Issue by maxTarlov** [syntax-prosody-ot/main#184]
We don't have a way of clearing trees out of the interface so when you switch between the two built-in analyses, you end up with the trees for both analyses. They just keep adding up, so you might unwittingly end up with 30 trees and the only way to get rid of them is to reload. I can clear out the JSON string in the tree code box easily, but the UI trees remain and I'm not sure how to clear them out.

**Comment by jbellik** [comment]
Oops, I didn't think of that. I can fix this. Where does this need to be triggered? I can think of:
- when you load a built-in analysis
- when the "Clear" button is clicked
Anywhere else that comes to mind?

**Comment by maxTarlov** [comment]
I think it would need to happen when a user loads a saved analysis too. If it is called in clearAnalysis, the trees will clear when a built-in analysis or saved analysis is loaded and when the clear all button is pressed

**Comment by jbellik** [comment]
Sounds good.
