### ISSUE TITLE
Binarity(leaves)

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#20]
Implement BinMax(cat,leaves). Currently, BinMax(phi,leaves) = BinMax(phi,w), but there is no BinMax(i,phi) or BinMax(Ft,syl), etc.

**Comment by jbellik** [comment]
The constraint function is currently named binMax2Words. The check for children of category 'w' is hard-coded into the function. It should be replaced with a check for children of the next lower category. I.e, if cat is 'phi', then check for 'w'; if cat is 'i', then check for 'phi'; if cat is 'w' then count feet (or syllables?). You may need to refer to prosodichierarchy.js for relevant functions.

**Comment by jbellik** [comment]
This change needs to happen for binMax2WordsGradient as well.

**Comment by jbellik** [comment]
4 constraints to be generalized:
- binMax2Words
- binMax2WordsGradient
- binMin2Words
- binMin2WordsGradient
