### ISSUE TITLE
should selecting "select one" again clear all the constraints (set back to blank)?

### ISSUE THREAD

**Issue by rbibbs** [syntax-prosody-ot/main#202]
Because currently the clear all button is at the bottom of the page and for first explorers of the interface it might be unintuitive how to uncheck everything. This is especially true on Firefox where refreshing doesn't clear all the constraints (a separate important issue).

**Comment by jbellik** [comment]
That seems like a weird way to clear everything to me. How standard is
that? I'd like to defer to Iva's UX knowledge on this; I assume she had a
good reason for putting those buttons at the bottom of the page. I guess my
hope is that with everything collapsed, the bottom of the page is not that
far...

**Comment by ivpetkov** [comment]
I asked at the meeting if we should consider implementing this, but I'm not totally sure if it's necessary. My reasoning was that if someone accidentally checks a built-in analysis they would be able to correct their mistake without scrolling to the bottom, but the clear button would still exist at the bottom. It is expected that if you make a selection in a dropdown, and then when selecting the default option your original selection is undone. However, I think this pattern is more for when a dropdown acts as more of checkbox versus in SPOT where a selection in the dropdown results in filling out the entire form. Basically, now that I think about it more, I don't think that it necessary for the default option to clear everything.

**Comment by jbellik** [comment]
Okay, let's not bother with this, then.
