### ISSUE TITLE
Clear all does not hide the tree builder

### ISSUE THREAD

**Issue by rbibbs** [syntax-prosody-ot/main#203]
Is this intended? Should it hide it? I think it probably should

**Comment by jbellik** [comment]
I agree, it should collapse the tree builder as well.

**Comment by jbellik** [comment]
Unless @maxTarlov or @ivpetkov is in the middle of working on this one, I'm going to assign it to @ColinAChen  to do this one since he's already worked on showing/hiding the tree-builder.

Please reply and assign/unassign yourselves if you're working/not working on this.

**Comment by jbellik** [comment]
Fixed.
