### ISSUE TITLE
Save/Load Custom Match Constraint

### ISSUE THREAD

**Issue by maxTarlov** [syntax-prosody-ot/main#212]
Make Save/Load/Built-in compatible with the custom match constraint

**Comment by jbellik** [comment]
Remind me what the status of this is? Is custom match is compatible now with save/load but not built-in?

**Comment by maxTarlov** [comment]
Currently neither works with the maximality and minimality options for the custom match constraint

**Comment by maxTarlov** [comment]
updated in pull request #280
