### ISSUE TITLE
find out if AlignLeftClitic works with built-in systems, save, load

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#223]

**Comment by jbellik** [comment]
I just made an adjustment to built_in_con() to make it work with that. But I imagine save/load will need something else.

**Comment by maxTarlov** [comment]
I have the code for the save function in the branch where I am working on NVH's built-in. I will test that both of these things work together before opening a pull request.

**Comment by maxTarlov** [comment]
Both working, in pull request #237
