### ISSUE TITLE
Moving multiple clitics

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#242]
@rbibbs tells me that Dan (another linguistics grad here) is working on a clitic movement phenomenon in a language related to Chamorro (Sulawesi?) that is very similar to the clitic movement that Richard is working on. It would be nice to be able to model both in SPOT and find both languages (hopefully) in the OTWorkplace typology. 

However, the other clitic movement pattern involves moving multiple clitics, which we don't currently support (since it's going to explode the number of candidates!).  I'd like to build back-end support for moving two or maybe three clitics -- with appropriate warnings to the user. We can decide as we find out more about the Sulawesi dataset how to move forward with this and whether to put it on the interface.

**Comment by maxTarlov** [comment]
Following Jenny's advise, I wrote a function that just permutes _all_ of the word orders when there is more than one clitic, but before Jenny gave me that advise, I had already written a function that collects the ids of all of the clitics in GENwithCliticMovement. Should I write a function that goes through and removes permutations where only non-clitics moved? I feel like this would be less confusing for the user, and while it wouldn't speed up GEN, it would speed up EVAL, which I think would be good.

**Comment by jbellik** [comment]
That's a good idea. Can you make it an option? I think we might eventually
want to also consider data sets where full w can move too.
