### ISSUE TITLE
GEN option: restrict trees to being n-ary (user specifies n)

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#249]
Could we add a GEN option to limit prosodic branching to be maximally binary? (Like "Only generate branching constituents", but for BinMax(pCat,branches) instead of BinMin.)

**Comment by jbellik** [comment]
Add a GEN option similar to noUnary that defines an upper limit on the number of branches a node can have (i.e., if you set it to k, you will get trees that are maximally k-ary).

**Comment by jbellik** [comment]
Simple implementation: use the function ternaryNodes() in syntaxFilters.js to exclude candidates in window.GEN_impl that have a node with more than maxBranches children.
