### ISSUE TITLE
New StrongStart

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#258]
I'd like to propose a version of StrongStart that is not satisfied by (ω ω φ). Specifically:

Assign one violation for every node in the prosodic tree whose leftmost daughter is of the selected category, and is lower in the prosodic hierarchy than some sister constituent to its right.

This could have a subcategory version too.

**Comment by nkalivoda** [comment]
Actually here's a version that I think is better, because both (ω ω φ) and (σ ω φ) violate it:

strongStartNew-pCat
Assign one violation for every node P of category pCat whose leftmost daughter is lower on the prosodic hierarchy than another daughter of P.

The default category should be phi, not w.

**Comment by jbellik** [comment]
I implemented this under the function strongStart (*not* strongStart_Elfner which is the one on the interface), which we had written to look only at the first two nodes. I don't think we used it anywhere but correct me if you think we ought to preserve our original version of it...
