### ISSUE TITLE
Clitics in input generation

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#278]
Sub-issue of #247 Automatic input generation function.

Let's have an option: "Allow clitic in terminal string". If checked, then for every clitic-free input tree with _n_ terminals, there are _n_ additional input trees of the same shape, in which one terminal is a clitic, such that every terminal is a clitic in exactly one of these trees. For example:

[a [b [c d]]]
[a-clitic [b [c d]]]
[a [b-clitic [c d]]]
[a [b [c-clitic d]]]
[a [b [c d-clitic]]]

**Comment by jbellik** [comment]
Implemented.

**Comment by jbellik** [comment]
We probably want to have some syntaxes in which the clitic is treated as a head, and others where it's a DP, as in preposition clitics vs. pronoun clitics.

**Comment by jbellik** [comment]
'a b c d' --> ['a b c d', 'a-clitic b c d', 'a b-clitic c d', 'a b c-clitic d', 'a b c d-clitic']
then run input GEN on each of those terminal strings (such that things labeled 'clitic' get category 'clitic')
