### ISSUE TITLE
NoShift definition and multiple movement

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#286]
Current definition of NoShift:

> Assign a violation if the terminals in the prosodic tree do not maintain the same precedence relations as those in the syntactic tree.

If we really end up adding functionality for multiple clitic movement (Issue #242), does that mean there's only 1 violation regardless as to whether one or more clitics move? That's how I read it right now. If not, then the definition will need to be updated.

**Comment by jbellik** [comment]
Yes, that's right. It only ever returns 1 or 0. It's actually not even a recursive function.
