### ISSUE TITLE
Gradient NoShift as Linearity

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#293]
If we try to implement a gradient NoShift, one possibility would be to use McCarthy & Prince's (1995) constraint Linearity.

> **Linearity** (McCarthy & Prince 1995, "Faithfulness and Reduplicative Identity")
> S₁ is consistent with the precedence structure of S₂, and vice versa.
> Let x, y ∈ S₁ and x', y' ∈ S₂.
> If xℜx' and yℜy', then
> x < y iff ¬(y' < x').

S₁ is the input string, S₂ is the output string, 'ℜ' is the correspondence relation, and 'p<q' means 'p precedes q'.

SPOT version:

> **Linearity** (McCarthy & Prince 1995 applied to terminal strings)
> For every pair of terminals (x,y), assign a violation if x precedes y in the terminal string of sTree and y precedes x in the terminal string of pTree.

Example with moving X:
<img width="400" alt="Screen Shot 2020-02-08 at 12 00 39 PM" src="https://user-images.githubusercontent.com/12573882/74084810-ad239300-4a6a-11ea-8e27-b11a8ed906b2.png">

Selected candidates with potential movers X,Y:
<img width="492" alt="Screen Shot 2020-02-08 at 12 00 47 PM" src="https://user-images.githubusercontent.com/12573882/74084815-b90f5500-4a6a-11ea-89be-23d4db145cf1.png">

Please correct me if I have misunderstood or miscounted anything.

**Comment by jbellik** [comment]
Create a helper function that takes a tree and gives back its terminal string. Use the code at the beginning of noShift for this.

**Comment by jbellik** [comment]
I would do this by making 2 NxN tables of the precedence relations among the N terminals (in the input and in the output). Then compare them and count up with cells that are marked "true" in the input table and "false"  in the output table (but *not* the reverse, false in input and true in output)
