### ISSUE TITLE
*pCat

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#294]
Let's add a constraint *pCat that assigns a violation for every pCat in pTree, i.e. *ι, *φ, *ω.

Very easy to do in OTWorkplace, but having it on the interface would allow us to add built-in systems from Truckenbrodt (1999).

**Comment by nkalivoda** [comment]
Since we can't use the asterisk, I suggest using "no".

**Comment by nkalivoda** [comment]
Unclear what section we would put these in on the interface. They're general *Struc constraints.

**Comment by jbellik** [comment]
"Layering" could become "Layering and Structure" and they could go in there?
