### ISSUE TITLE
Input Gen option: Remove mirror images

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#312]
Input Gen option to remove trees that are mirror images of trees earlier in the list.

Definition of mirror image:
Ignoring ids, but not cats, the mirror image of a tree T is a tree T' in which every children array in T is in reverse order in T'.

Example:
T  = [x0 [x0 [x0]]]
T' = [[[x0] x0] x0]

Reason to have this option:
If Con doesn't contain any mirror-distinguishing constraints (e.g. AlignL, AlignR, StrongStart), then for every language in the typology, a mapping sTree→pTree entails the mapping mirror(sTree)→mirror(pTree). Unnecessary to look at all of the mirrors (which can be numerous).

Not equivalent to imposing a left- or right-headedness requirement. If "remove mirrors" were selected, then one of either [x0 [[x0] x0]] or [[x0 [x0]] x0] would be an input (whichever one happens to be earlier in the unfiltered list), even though neither of these is generated when headedness is restricted to one side.

**Comment by nkalivoda** [comment]
This should only apply if sTree≠mirror(sTree). We wouldn't want to exclude a tree like [[x0] [x0]].

**Comment by nkalivoda** [comment]
Question that arose in meeting: Is it possible to write a phrase structure grammar that doesn't generate mirror(T) when T≠mirror(T)?

**Comment by jbellik** [comment]
Currently, this seems to remove symmetrical outputs -- it is pruning out too many.
Allow mirrors: [[a] b], [a [b]], and symmetric [[a][b]]
Exclude mirrors: should yield [[a] b] and symmetric [[a][b]] (excluding [a [b]] -- or we could keep this one and exclude [[a] b])
Currently exclude mirrors only yields: [[a] b] and incorrectly leaves out [[a][b]]

**Comment by jbellik** [comment]
For the three word case, too many are excluded as well. Checking "remove mirror images"
should include the first six (highlighted in blue), not just the first three as it currently does.
![image](https://user-images.githubusercontent.com/12523306/78182529-35933400-741b-11ea-8f7e-4e93c0c05683.png)
