### ISSUE TITLE
Pictures of trees

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#327]
Question, probably for @ozanblk: Would it be hard to add a function that allows you to download pictures of all of the trees in the tree-builder? I take screenshots of them individually so that I can look at them later (even though I also save the code), but this is quite tedious. If it would be really complicated, it's no big deal.

**Comment by ivpetkov** [comment]
The best way I've found is to use the html2canvas library: http://html2canvas.hertzen.com/getting-started

We would need draw the div containing the trees into a canvas element, then use the HTMLCanvasElement object's toDataURL function to get a data URI with the image's contents, then open the image in a new tab where the user can save it.
