### ISSUE TITLE
noAdjacentHeads options on interface

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#373]
Currently, with auto input generation on the interface, noAdjacentHeads is always true; there is no way to set it to false. This creates two problems:

1. If you want to build compound word syntaxes by picking x0 as the intermediate category, you get no results (since this would require adjacent heads)

2. We want to add an option to leave out unary XPs and turn them into plain x0s, which would also require adjacent heads in the outputs. [[a] b] --> [a b]

**Comment by jbellik** [comment]
Let's change interface1.js to automatically set noAdjacentHeads to false if you pick either of the following:
- intermediate category : x0
- unary XPs are invisible (new option that we need to implement, which sets noUnary:true, noAdjacentHeads: false)

**Comment by maxTarlov** [comment]
do we want the check to happen when the value of intermediateCategory/terminalCategory/noUnary changes or when sTreeGEN is run? If we run this visually in the interface (on change) I can disable the noUnary option while while the other options are incompatible.

**Comment by maxTarlov** [comment]
correction: I would set the noAdjacentHeads input to disabled, not noUnary.
