### ISSUE TITLE
Missing candidates

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#394]
The version of the interface on Jenny's website is giving incomplete csets, at least for the Gen used in the built-in Japanese systems from NINJAL. It's leaving out 4 candidates for "a b c" (it gives 20 instead of 24), and 40 candidates for "a b c d" (136 instead of 176).

Luckily, the latest version of the interface on Github seems to be working fine.

@jbellik, could you update the interface on your website?

**Comment by jbellik** [comment]
The website has been updated.
