### ISSUE TITLE
More missing candidates(?)

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#396]
I've just built. Hopefully I haven't forgotten to do anything else!

I just tried Gen with φ-wrapping, recursivity, and no unaries on an 8-word input. On the interface (the version on Github, not on the website), I got 3494 outputs, but with an analysis file I got 4279. The latter is the correct number, since it is the 7th Super-Catalan number.

**Comment by jbellik** [comment]
Can you push the analysis file to Github (to a new branch if you like, or to master if you haven't made changes in other files) so I can compare the settings the interface selects in the backend for those selections to the ones you used in the analysis file?

**Comment by jbellik** [comment]
Nevermind, I found the bug causing this in candidateGenerator. I had introduced a > that should've been < that affected the wrapInRootCat function when rootCategory === recursiveCategory. This change was introduced when I was working on the compound prosodic words GEN and I'm not sure how it got into the master branch. It's now fixed (at least for the 8-word input with the settings you mentioned).

**Comment by jbellik** [comment]
I think this fix also fixed the problems with the compound prosodic parses!!!

**Comment by nkalivoda** [comment]
Excellent, thank you!
