### ISSUE TITLE
Info for tree display options

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#398]
We need to add info for "annotated with tones" and "mark heads" under "Tree display options". I could do it for the tones, but I don't know how the head-marking works.

**Comment by jbellik** [comment]
There is already info for the tone annotation that is language-specific. That is, if you select "Annotated with tones", then the options "Japanese" and "Irish" appear, and each of those has an associated info button. Do we need a general info button too?

The head-marking procedure is explained in #275 .
