### ISSUE TITLE
Custom MatchPS with Lexical and Overtly Headed settings

### ISSUE THREAD

**Issue by nvh4** [syntax-prosody-ot/main#422]
When choosing a Custom MatchPS constraint in the interface and selecting Lexical and/or Overtly Headed, every candidate is assigned zero violations.

Additionally, the interface says "Enforce Match only for prosodic nodes that are... {lexical, overtly headed}." However, even though this is a PS constraint, these options still apply only to the syntactic nodes. Thus, for a Custom MatchPS(Lexical), the constraint should assign a violation to any phi that does not have a corresponding lexical XP in the syntax. This might be the source of the problem with the violations.

**Comment by jbellik** [comment]
On the interface, "lexical" and "overtly headed" should move down into the "Syntactic categories must be..." part of Custom MatchPS
