### ISSUE TITLE
"Syntax parameters"

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#423]
A. Make this fieldset expanded by default

B. Break it into 3 parts:
1. Syntactic parameters: Root syntactic tree in, Intermediate nodes are, Terminals are, Include adjunction (currently "Allow adjuncts"), Head requirements
2. Clitics: Add XP clitics directly under the root, Label some terminals as clitics (currently "Allow clitic in terminal string")
3. Visibility to phonology: Treat unary XPs as X0s (currently "Unary XPs are invisible"), Treat intermediate projections (bar levels) as phrasal (currently "Bar levels are invisible"; need to flip the logic on this from the current configuration -- make it checked by default and flip the true value to false and vice versa).

Currently not sure where to put the "Remove mirrors" option.

More refinements to come...

**Comment by jbellik** [comment]
When "Treat intermediate projections (bar levels) as phrasal" is checked, then maxBranching = 2 and only the first 3 Head requirements options should be available
When not checked, maxBranching = 3, also need to enable all 5 of the Head requirements options
--> check all the places that noBarLevels is used and flip === to !==

Also make 3 fieldsets. Syntactic parameters open by default, others closed.

**Comment by rbibbs** [comment]
@jbellik I like the proposal for the three part distinction. "Visibility to phonology" already makes it more clear as to what the options do and what it means for a functional representation. I also like the renaming of the options within the aforementioned visibility part.

I've also attached a doc outlining a couple potential issues with the tree generation we should address. Several of these issues deal with headedness and CP roots. [](https://docs.google.com/document/d/1DYZyrnekH_xfGVi3rCbcMnf5-zWyG9pZif9Bk64gMZI/edit?usp=sharing)
