### ISSUE TITLE
Cache busting the interface

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#43]
change interface to ensure that spot.js is loaded freshly instead of potentially using what's in cache (which may be out of date).

**Comment by jbellik** [comment]
will require more sophisticated build.sh script -- but that won't work in Windows .bat.

**Comment by maxTarlov** [comment]
FYI: when making the built-in analyses for the interface, I added a "clear" button which reloads the page and clears out the cache.
