### ISSUE TITLE
X0 as intermediate category and head alignment options

### ISSUE THREAD

**Issue by rbibbs** [syntax-prosody-ot/main#432]
If x0 is selected as the intermediate category, then you shouldn’t be able to select anything for “Head requirements”. Disable everything other than “Heads can be anywhere.”

**Comment by jbellik** [comment]
Richard, did you mean to assign this to yourself? I was thinking I'd have one of the undergrads do it, but you can try to tackle it if you like.

Further info. in case someone else ends up assigned to this: This issue pertains to the "Syntax parameters" part of GEN: Inputs on the interface.
