### ISSUE TITLE
Tones for Irish

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#44]
For looking at Irish, it might be helpful to be able to add tones on a line under the φ-structure. According to Elfner (2012), these are:

- L*H on leftmost ω of every nonminimal φ
- H*L on rightmost ω of every φ

**Comment by nkalivoda** [comment]
Putting this on the interface would involve distinguishing between the options "Add tones for Japanese" and "Add tones for Irish".

**Comment by jbellik** [comment]
This has been implemented and works fine when it's run on trees in a for loop outside of GEN. But when called from GEN (when addTones option is used), it doesn't recognize that any phis are non-minimal?! so there are no LHs annotated.

**Comment by jbellik** [comment]
Update: It seems this was an issue with GEN overwriting things. For some reason it wasn't an issue with Japanese tones -- or if it was, it wasn't noticeable...
