### ISSUE TITLE
Disambiguate categories in bracketed representations

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#45]
Bracketed representations of syntactic trees are currently showing [ ] for every non-terminal constituent in the tree, but we should reserve [ ] for nodes marked "cat":"xp".

CP should also be shown, but instead of [ ] we should use { }.

Any constituent that lacks a valid "cat" should not get brackets. This will allow people to label things "cat":"invisible" or "cat":"xbar" (or anything other than "xp", "cp", or "clause") without getting any brackets around them.

**Comment by jbellik** [comment]
Will also need to update whereever parenthesizeTree(stree, {parens:'[]'}) is called on the syntactic tree.

**Comment by jbellik** [comment]
Need to update the toneTree to ensure alignment depending on the various parenthesization options.
