### ISSUE TITLE
Change citation for Japanese built-in system

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#451]
Ito & Mester 2017 in the list of built-in systems should probably read Ito & Mester 2017/2020 since the book this paper is included in was actually published in 2020.

From Junko's website:
2020 | Ito, Junko, and Armin Mester. Match Theory and Prosodic Wellformedness Constraints. In Zhang, Hongming, and Youyong Qian, eds. Prosodic Studies. Challenges and Prospects. London and New York: Routledge. pp. 252-274.

**Comment by nkalivoda** [comment]
Done.
