### ISSUE TITLE
Headedness constraint

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#467]
We should have a constraint Headedness under "Layering and structure" in the non-hidden part. Both cat-sensitive and cat-insensitive as options.

**Comment by jbellik** [comment]
Constraint definition:
- Category insensitive: "For every category k in pCat (defined in prosodicHierarchy.js), assign a violation for every node of category k in the prosodic tree ptree that is a) non-terminal and b) does not contain any nodes of category > k-2."
- Category insensitive, for category k: "Assign a violation for every node of category k in the prosodic tree ptree that is a) non-terminal and b) does not contain any nodes of category > k-2."

Write the following function:

function headedness(stree, ptree, cat): Return the number of nodes in ptree that a) have children and b) do not have a child of the next lower category or the same category. 

If cat is defined, then only count nodes of category cat. If cat is not defined, count nodes of any category that lack a head.

Definition of head: a node of category k has a head if a) it is a terminal (we will assume it is headed, by default), or b) it contains a node in its array of children that is of category k or k-1. If all its children are of category k-2 or lower in the prosodic hierarchy (see prosodicHierarchy.js), then it is unheaded.

For example, a node of category cat: 'i' would be unheaded if its children are all of cat: 'w'. But it would be headed if it contains at least one node of cat: 'phi' (= category k-1) or cat: 'i' (= category k).

**Comment by jbellik** [comment]
This is a good starter issue.

Steps:
- Write and test the function.
- Add it to interface1.html. Test that it's working there.

**Comment by jbellik** [comment]
Prosodic hierarchy is defined main/prosodicHierarchy.js which contains an array pCat that tells you what order the categories occur in.

You can use pCat.nextLower(cat) to identify the next lower category which would be valid as a head.
pCat.isLower(cat1, cat2)

pCat.nextHigher()

**Comment by maxTarlov** [comment]
My availability to help: 
 * Today (10/6): all day
 * Wednesday (10/7): all day
 * Thursday (10/8): after 1:00 PM
 * Friday (10/9): after 1:00 PM
 * Saturday (10/10): not available
 * Sunday (10/11): all day, but not preferred
 * Monday (10/12): all day, but not preferred

**Comment by jbellik** [comment]
Su, I'm hoping @M130 is you!

**Comment by maxTarlov** [comment]
Backend debugged and working. @tijgee and @M130 take a look at the test file to make sure you understand what is going on and feel free to ask any questions

**Comment by jbellik** [comment]
Hi all, please open a pull request if this is ready for review!

**Comment by jbellik** [comment]
Tree bracketing interpretation example for reference: https://docs.google.com/drawings/d/1poP1VOFSG7Xwsl20QVlfqQBBJyXFE-Y8kfF9h5qBNd8/edit

**Comment by jbellik** [comment]
Goal for 10/20:
- Check a few more rows of the tableau in main/test/headednessConstraint.html to practice interpreting the brackets and confirm that the function is working correctly
- Add headedness constraint to main/interface1.html in the fieldset Layering and Structure, directly under Exhaustivity
- It should have four category boxes: iota, phi, w, and all (see: EqualSisters under the Sisterhood fieldset on the master branch). I recommend copying the entire div for "EqualSisters (by parent)" on the master branch, and just changing the function names appropriately in the tags and text.

Feel free to set up an additional meeting with me, Max, or Ed if you'd like to talk through how interface1.html is organized.
