### ISSUE TITLE
Combinations and permutations input validation

### ISSUE THREAD

**Issue by maxTarlov** [syntax-prosody-ot/main#491]
When "generate terminal strings" is clicked, the user has no good way of knowing if they used invalid inputs. Invalid inputs sometimes throw cryptic errors that can't be seen outside of the console (maximum call stack exceeded), and sometimes just do nothing at all. interface1.js should check that for each string

- [ ] min and max are non-zero, positive integers
- [ ] min is less-than or equal to max
- [ ] neither min nor max is large enough to cause performance or display issues

**Comment by jbellik** [comment]
Use the displayError() function -- I think it's defined in interface1.js

**Comment by jbellik** [comment]
Error if max or min is 10 or greater 
Warning if max or min is greater than 5

Error/warning message should say something about how it will generate too many terminal strings and may cause your browser to freeze. The number of terminal strings of length n generated from a set of m different terminals will be n to the power m.

**Comment by jbellik** [comment]
Try: Drop down menu solution
- check that it works with save/load: use Max's unit tests for save/load -- these might not be in master
- refer to code for built-in systems and for Head requirements under Syntax Parameters
- if drop down menu solution ends up more complex than current solution in the pull request, we can abandon that tack and go back to the original solution

**Comment by jbellik** [comment]
Do this in a separate branch, possibly based on "save_load_update" branch to get the unit tests.

**Comment by jbellik** [comment]
Copied over from Max's comment on the pull request:

Unit Tests for save/load have been merged into master, no need to merge from save_load_test
To run unit tests on this:

run testBuild.sh
open interface1.html
in JS console, use runStringTest()
mocha reporter should appear at the top of the page
N.B. the unit tests right now use numbers out of the range that you have defined. If that makes the test fail, you can change them in the unit test code, i am working on a better way to check that things have saved

**Comment by M130** [comment]
I tried the drop down options and we should probably just stick with the non-drop down option. I can get the value of the first terminal min and max but I can't find a way to get the value from terminal 2 and onward. I still commit the changes I tried which is in save_load branch.
