### ISSUE TITLE
"Inputs of more than 6 terminals..." warning

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#492]
On the interface, this warning displays once for every input with length > 6. It would be better to only show it once, so users with several long inputs only have to click "continue" once.

**Comment by M130** [comment]
Inputs of more than 6 terminals warning for generate combinations and permutations terminals?

**Comment by jbellik** [comment]
This warning is triggered when "Get results" is clicked and one or more input from anywhere in the GEN: Input parameters has more than six terminals. The warnings are being generated in main/interface1.js lines 514 - 530.
