### ISSUE TITLE
Convert console logging test files to Mocha tests

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#502]
@maxTarlov  will update this issue with a list of existing manual test files that currently log all information (+ expected values) in the JS console. 

These should be converted to Mocha tests.

**Comment by maxTarlov** [comment]
I created a branch (**logging2mocha**) where the aforementioned test files are moved back to the test/ directory and use the correct paths for resources. The test file are:
* binMaxHeadTest.html
* binMaxPhiTest.html
* containsAdjunctTest.html
* gen_terminal_strings_test.html
* headAlignBugTest.html
* mirror_test.html
* noShiftGradient.html
* threeXPsTest
