### ISSUE TITLE
"Mapping" and "Markedness" macro-sections

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#518]
I think it would be nice to divide the constraint sections into two macro-sections: Mapping and Markedness (if you agree, @jbellik).

Mapping:
- Match
- Align/Wrap
- Command

Markedness:
- Ordering
- Binarity
- Sisterhood
- Layering and structure
- Pitch accent

I might want to add markedness Align constraints at some point, so it would be important to have mapping Align in its own section. But even now, I think it would be good to emphasize the distinction.

**Comment by nkalivoda** [comment]
And let's have info for each macro-section.

Mapping info:
- Mapping constraints refer to both syntax and prosody. They are similar to faithfulness constraints in that they regulate the relation between input and output (Prince & Smolensky 1993/2004, McCarthy & Prince 1995), but are distinct from faithfulness since syntactic and prosodic trees are built from different atoms (e.g. XPs and φs) as opposed to elements from the same alphabet (e.g. segments). Mapping constraints include constraints from competing theories, e.g. Match vs. Align/Wrap.

Markedness info:
- Markedness constraints refer only to outputs, not to inputs (Prince & Smolensky 1993/2004). In SPOT, this means that they inspect only the pTree in each candidate ⟨sTree,pTree⟩.

**Comment by nkalivoda** [comment]
Also for mapping info: "Mapping constraints come in two types: syntax→prosody and prosody→syntax."

**Comment by jbellik** [comment]
I like this idea but Ordering needs to be with the mapping constraints. I'm about to try out an implementation of this.

**Comment by nkalivoda** [comment]
Oooh, yeah, you're right!

**Comment by jbellik** [comment]
Closed by #536
