### ISSUE TITLE
"SPOT function" in constraint info?

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#524]
Some of the constraints have the SPOT function in the info, e.g. "SPOT function: equalSistersAdj()". Others lack it, e.g. "EqualSisters (by parent)", and others have it but withtout the "()", e.g. "SPOT function: equalSisters2".

I am assigning myself the task of making them consistent, but @jbellik, could you weigh in first on what the official style should be? Should we always include it, and with the parentheses?

**Comment by jbellik** [comment]
Hmm. I think it's good to list the SPOT function for clarity about which code is being used. Of course, it's possible to reconstruct this info from the html as well, but that's a lot harder to interpret. The () after the function name look a little funny but are useful for showing clearly that it is a function. So I'd like to either a) keep the () everywhere, or b) italicize all the function names or do some other styling to indicate their special status.

**Comment by nkalivoda** [comment]
I think it would be best to use () everywhere. I'll do it.

**Comment by jbellik** [comment]
Thank you, Nick!
