### ISSUE TITLE
WeakStart

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#525]
Constraint from Sabbagh (2014, p. 62) "Word Order and Prosodic-Structure Constraints in Tagalog":

> Weak Start: *(π₁π₂..., where π₁ > π₂
> A prosodic constituent begins with a leftmost daughter that is no higher on the prosodic hierarchy than the constituent that immediately follows.

**Comment by jbellik** [comment]
- make basic test file
- add to interface under Sisterhood, at the very bottom of the "show StrongStart variations" section
