### ISSUE TITLE
StrongEnd

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#526]
StrongEnd, a constraint mentioned *but rejected* by Bellik, Ito, Kalivoda, & Mester (to appear, p. 16 of PDF draft):

> StrongEnd (reverse of Elfner's 2012 StrongStart; to be rejected)
> Assign one violation for every node in the prosodic tree whose rightmost daughter is of category ω and is lower on the prosodic hierarchy than its sister immediately to its left.

**Comment by jbellik** [comment]
Is this to go on the interface? I just did a very quick implementation of it but haven't done rigorous testing.

**Comment by nkalivoda** [comment]
I think it should go on the interface – but buried way down under "Show more...". I think it's a natural thing to wonder about, even if it shouldn't be adopted.

**Comment by nkalivoda** [comment]
I think the same about WeakStart in #525.

**Comment by jbellik** [comment]
Minimally tested first passes of these constraints are in the branch strongEnd. They have not been added to the interface there, and also lack test files.

**Comment by jbellik** [comment]
- make basic test file
- add to interface under Sisterhood, at the very bottom of the "show StrongStart variations" section
