### ISSUE TITLE
More info with re-ordering Gen

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#530]
We should add some more info to the re-ordering options in the input Gen section. Specifically: how do the mapping constraints interpret ⟨sTree,pTree⟩ pairs when the terminal strings are distinct due to re-ordering?

(I don't mean theoretically, I mean: how does it actually work with the mapping constraints we currently have.)

**Comment by jbellik** [comment]
The Match constraints compare sets of terminals, without regard to order, just like in Bennett et al 2016.

**Comment by jbellik** [comment]
I just added this info to MatchSP and MatchPS, but did not add it to the other Match constraints.
