### ISSUE TITLE
Match-any

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#544]
1. Check if Match-any is broken due to the checking of the prosodic hierarchy. Error checking in makeTableau() probably needs to be made more nuanced to only check that the category is in pCat if it's not "any" or "". Two other possible ways to handle this are (1) to change the way we refer to the category in category-insensitive Match to just not specify a category at all, or (2) change the category-check to just create a warning rather than throwing an error. 

2. Add interface support for "Match-any" (Match that ignores syntactic categories) by adding a checkbox with value 'any'.

**Comment by jbellik** [comment]
Create Mocha tests for this too.

**Comment by jbellik** [comment]
On the interface, make MatchSP-any look visually consistent with StrongStart-global and StrongStart-local (under Markedness > Sisterhood).

**Comment by jbellik** [comment]
See test/manual_testing/matchOptions.html as an example of a file that is broken currently & should not be.

**Comment by M130** [comment]
matchSP(inputTree, ptree, any) = /= matchSP(inputTree, ptree, 'xp') + matchSP(inputTree, ptree, 'cp') when testing. matchSP(inputTree, ptree, any) also seems to be counting things categorized as "x0" or "c0" etc. Is that right or does it need to be corrected?
