### ISSUE TITLE
auto testing by Github

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#547]
Goal: To take advantage of Github's "Actions" to automatically run various tests whenever a pull request comes in.

To do this, we need all the (relevant) Mocha tests to be in .js files by themselves. 
- I think the tests can then be called from the existing html test files to provide a visual / more detailed information for when they fail. 
- Each JS test file with Mocha tests in it can be compiled into a big test.js file (akin to constraints.js).
- Then the workflow yml script will run test.js every time a pull request comes in.

**Comment by jbellik** [comment]
Sub tasks:
- [ ] pull Mocha tests out of existing html auto test files into separate .js files
- [ ] change existing auto test html files to run the code in the .js files
- [ ] write a new testbuild.sh script, or modify the existing one
- [ ] change the yml script to use test.js

**Comment by jbellik** [comment]
First step would be to try pulling the Mocha code/script out of *one* of the existing automated test files and adding a line to the workflow that runs it

**Comment by M130** [comment]
When pulling mocha tests out of existing html into .js files, do you mean find a command that does that or change the test files manually like with the interface test files or either or?

**Comment by jbellik** [comment]
As a first step, let's take the mocha tests out manually from one html file. That will give us a .js file, let's call it test1.js, that (I hope) can be used both in the html file and in the Github action (in the yml file). Then try adding a line to the .yml file that runs test1.js.

**Comment by M130** [comment]
start with stringTest.js

**Comment by M130** [comment]
branch github

**Comment by jbellik** [comment]
Since stringTest.js is using the interface, let's actually start with extracting the script from binarityTest.html into binarityTest.js.

**Comment by jbellik** [comment]
Possibly we also need to install chai in the yml script.

**Comment by jbellik** [comment]
mocha.setup("bdd"); //brings "describe", "it", etc. into global namespace
        //mocha.checkLeaks();
        var assert = chai.assert;

Ultimately these lines also need to get into the yml or into the compiled test.js file, but for now, just grab them along with the rest of the binarity tests and put them at the top of binarityTest.js.

**Comment by M130** [comment]
It seems that I need to first merge my code with master branch to be able to test it in github actions. Is there another way to test it first without merging?

**Comment by M130** [comment]
https://gist.github.com/soheilhy/867f76feea7cab4f8a84
https://www.freecodecamp.org/news/what-are-github-actions-and-how-can-you-automate-tests-and-slack-notifications/
https://docs.github.com/en/actions
https://github.com/actions/checkout/blob/main/.github/workflows/test.yml
https://stackoverflow.com/questions/9722407/how-do-you-install-and-run-mocha-the-node-js-testing-module-getting-mocha-co

**Comment by jbellik** [comment]
Some general info on using Mocha in the terminal: 
- If a package.json file is present, you can specify test: "mocha". Then running npm test will automatically run all the js files in the test directory: test/*.js
- Since we haven't set SPOT up to be modularized, we have to put spot.js *in* test.js in order to access all the functions without messing around with refactoring to use import or require.

**Comment by jbellik** [comment]
Largely addressed by #567 
Running mocha in the console requires installing node. If you have node installed on your local machine, and have pulled package.json into your local repository, you can check whether all the tests in main/test/compiledTest/test.js are passing:
Step 1: From main, run ./mochabuild.sh. (NB I have *not* written a .bat version of this build script!) This will create test.js in the directory main/test/compiledTest.
Step 2: Also from main, run npm test, which will evaluate the 400+ tests in test.js and output results to the command line.
But Github will also run all those tests for you when you set up a pull request to master, if you don't want to set node up locally. I did add node_modules to the .gitignore file so they don't end up in the repository.

Remaining tasks to finish setting up Github's auto testing:

- [ ] extract test functionality from the following files and put it in corresponding JS files, wrapped in a function that the html file calls: 
- binMaxHeadTest.html -- that one is related to the headmarking debugging that Ed is working on
- narityTest.html
- noShiftGradientTest.html
- strongStartHsuTest.html
- syntacticFiltersTest.html. 
- See other test files for working examples. Ex: binarityTest.js and binarityTest.html 

- [ ] write .bat version of mochabuild.sh -- mochabuild.bat
- [ ] update jsbuild.bat and maybe testBuild.bat to match jsbuild.sh and testBuild.sh. The current changes are: (1) make top.js as a distinct build file -- top.js needs to go into compiledTest/test.js for mocha testing, but we don't want interface.js to go in it because it makes reference all over the place to the window/broswer which the Github auto testing cannot handle. (2) make a build/test.js that excludes the mocha files, since we don't want those in compiledTest/test.js either, since we install mocha separately in that virtual machine.

**Comment by jbellik** [comment]
@M130 Could you work on this some more? Take a look at the post just above this and let me know if you have questions. Basically you can test it all locally if you install node; I set up the package.json file and changed the .gitignore to ignore the node files, so it won't mess up the repository even if you put it in your local repository folder. 

I'm thinking it should be pretty easy to deal with the rest of the test files (listed in the post above) and you could probably manage that before Wednesday. But you'll need to update the .bat files to test it, if I'm remembering correctly that you're on a Windows machine.
