### ISSUE TITLE
Frontend testing

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#585]
Research: How do we test html in Github actions?
ex: https://www.joshkasuboski.com/posts/htmltest-githubactions/

Goal: to have automated frontend testing, starting the Google Doc of test cases for various inputs that you already set up.

**Comment by M130** [comment]
Could you allow me to commit to the main branch for github action file? Thanks!

**Comment by M130** [comment]
@jbellik I just found out that Selenium WebDriver requires an account to use it. I am going to try to find another way to do frontend testing without using it.
