### ISSUE TITLE
CSV file for OTWorkplace

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#6]
It's easy enough to make the necessary alterations by hand after copying and pasting the CSV file into Excel, but ultimately we'd like the following formatting:

- Row 1 should be left empty.
- Column C should be left empty.
- The constraint names should start in Cell D2 and continue along Row 2.
- The list of outputs should begin in Cell B3.
- The input for each list of outputs should go in the cell in column A that is adjacent to the first output in the list.

For example:

![otw formatting](https://cloud.githubusercontent.com/assets/12573882/7991007/d584e8cc-0aa9-11e5-81ef-7e75f59484fd.png)

**Comment by ozangds** [comment]
Caveat for the resolution: we're only supporting a single input tree right now.
