### ISSUE TITLE
Implement NoShift constraint

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#70]
NOSHIFT (Bennett et al. 2016): If a terminal element α is linearly ordered before a terminal
element β in the syntactic representation of an expression E, then the phonological exponent
of α should precede the phonological exponent of β in the phonological representation of E

- Implementation 1: categorical. Assign a violation for every terminal element a that precedes b in the linearization of the stree and does not precede b in the ptree.

- Implementation 2: gradient evaluation of distance. Assign a violation for every node n of category cat that intervenes between terminal elements a and b in the prosodic output that are linearly ordered a > b (a preceding b) in the syntactic input.

EDITED to remove "immediately" from the categorical definition in line with the original Bennett et al proposal

**Comment by jbellik** [comment]
Richard, please verify the constraint definitions above and confirm that the categorical implementation doesn't need to be parameterized with any syntactic or prosodic categories.

**Comment by rbibbs** [comment]
The current categorical implementation of NoShift should be totally fine as is. The order of terminal elements is all that the constraint needs to evaluate; no other syntactic or prosodic category should be relevant for the categorical version.

The gradient implementation definition also looks good!

**Comment by jbellik** [comment]
Super categorical implementation: Assign a violation for a ptree, stree pair such that the terminal string for ptree is not linearly ordered the same as the terminal string for stree.

**Comment by jbellik** [comment]
Theoretical question here: Is NoShift supposed to do the job of Contiguity, or of Linearity? cf. work on metathesis, prothesis, epenthesis
