### ISSUE TITLE
Equal Boundary Strength constraints

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#80]
**equalStrengthLeftSP**: For every word w in the sTree such that w is at the left edge of n syntactic constituents in the sTree, and w is at the left edge of m prosodic constituents in the pTree assign n-m violations if n>m.

**equalStrengthLeftPS**: For every word w in the sTree such that w is at the left edge of n syntactic constituents in the sTree, and w is at the left edge of m prosodic constituents in the pTree, assign m-n violations if m>n.

**equalStrengthLeft**: For every word w in the sTree such that w is at the left edge of n syntactic constituents in the sTree, and w is at the left edge of m prosodic constituents in the pTree, assign |n-m| violations.

There should also be right-edge versions. And although it says "word" here, it should really be category-neutral: cp<>i, xp<>phi, x0<>w.

**Comment by jbellik** [comment]
Closing since I am going to make this into several smaller tickets.
