### ISSUE TITLE
Remove spot.js and constraints.js from the repository

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#88]

**Comment by ozanblk** [comment]
Done. But current PRs will have merge conflicts that will need to be resolved.

**Comment by jbellik** [comment]
These merge conflicts have been resolved but we need to add some kind of support for downloading the build files for users who won't know how to build but still want to use the analysis html files!

**Comment by jbellik** [comment]
Build files are being maintained in a sister repository (syntax-prosody-ot/build)
